cache:
  directories:
    - perl_modules
before_install:
  - cpanm local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
language: perl
addons:
  apt:
    packages:
    - bedtools
    - cd-hit
    - ncbi-blast+
    - mcl
    - parallel
    - cpanminus
    - prank
    - mafft
    - fasttree
    - build-essential
sudo: false
jdk:
  - openjdk8
  - oraclejdk8
install:
  - "source ./install_dependencies.sh"
script: "dzil test"
